CREATE TABLE [dbo].[AccountStatus]
(
	[AccountStatusId] TINYINT NOT NULL IDENTITY(1,1) PRIMARY KEY, 
    [Name] NVARCHAR(256) NOT NULL, 
    [Active] INT NOT NULL DEFAULT 1,
	[LastUpdate] DATETIME NOT NULL DEFAULT GETDATE(), 
    [CreateDate] DATETIME NOT NULL DEFAULT GETDATE(),
)
